config/routes.rb
Fiveyeardiary::Application.routes.draw do

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match '/stats' => 'pages#stats'

  match '/signup' => 'identities#new', as: :sign_up
  match '/signin' => 'sessions#new', as: :sign_in
  match '/signout' => 'sessions#destroy', as: :sign_out

  match "/diary/day/:day" => 'notes#day_of_month', as: :day_of_month_diary
  match "/diary/:year/week/:week_number" => 'notes#week', as: :week_diary
  match "/diary/:month/:day" => 'notes#day', as: :daily_diary
  match "/diary/:weekday" => 'notes#week_day', as: :week_day_diary

  resources :notes, only: [:new, :create, :edit, :update]
  resource  :profile, only: [:edit, :update]
  resource  :settings, only: [:edit, :update]

  root :to => 'pages#home'

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord

  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates :password, :length => { :minimum => 6 }

end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :user

  validates :content, presence: true
  validates :date, presence: true, date: {before_or_equal_to: Proc.new {|note| Time.now.in_time_zone(note.user.time_zone).to_date }, message: "cannot be in the future"}
  validates :date, uniqueness: {scope: [:user_id], :message => "You have already made a note for this day"}

  scope :for_day, lambda {|month, day| where(month: month, day: day) }
  scope :for_week_day, lambda {|weekday| where(week_day: weekday) }
  scope :for_day_of_month, lambda {|day| where(day: day) }
  scope :for_week, lambda {|year, week_number| where(iso_8601_year: year, iso_8601_week_number: week_number) }
  scope :written_today, lambda { where(date: Date.today) }
  scope :since, lambda {|since_date| where(["date >= ?", since_date]) }
  scope :by_date, order(:date)

  before_save :split_date_parts

  def dom_id
    date.strftime('%Y-%m-%d')
  end

  private

  def split_date_parts
    self.iso_8601_year = self.date.strftime('%G').to_i
    self.month = self.date.month
    self.day = self.date.day
    self.iso_8601_week_number = self.date.strftime('%V').to_i
    self.week_day = self.date.strftime('%u').to_i
  end

end

app/models/setting.rb
class Setting < ActiveRecord::Base

  belongs_to :user

  validates :time_zone, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true, on: :update

  has_many :notes
  has_one  :setting

  def time_zone
    return 'UTC' if setting.nil?
    setting.time_zone || 'UTC'
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :set_time_zone

  protect_from_forgery

  helper_method :current_user, :user_signed_in?

  protected

  def authenticate
    if !user_signed_in?
      redirect_to sign_in_url, alert: "Please sign in first"
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  def set_time_zone
    Time.zone = current_user.time_zone if user_signed_in?
  end

end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController

  def new
    @identity = env['omniauth.identity'] || Identity.new
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter :authenticate

  def new
    @note = Note.new
  end

  def create
    @note = Note.new params[:note]
    @note.user = current_user
    if @note.save
      date = @note.date
      redirect_to daily_diary_url(date.strftime('%B').downcase, date.day, anchor: @note.dom_id), notice: 'Note saved successfully'
    else
      render :new
    end
  end

  def day
    @date = DateTime.current.change(month: month_number_for(params[:month]), day: params[:day].to_i)
    @notes = current_user.notes.for_day(@date.month, @date.day).by_date
  end

  def week_day
    @weekday = Date.parse(params[:weekday])
    @notes = current_user.notes.for_week_day(@weekday.strftime('%u')).since(5.weeks.ago).by_date
  end

  def week
    @notes = current_user.notes.for_week(params[:year], params[:week_number]).by_date
  end

  def day_of_month
    @day = params[:day].to_i
    @notes = current_user.notes.for_day_of_month(@day).since(5.months.ago).by_date
  end

  def edit
    @note = current_user.notes.find(params[:id])
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update_attributes(params[:note])
      date = @note.date
      redirect_to daily_diary_url(date.strftime('%B').downcase, date.day, anchor: @note.dom_id), notice: 'Note updated successfully'
    else
      render :edit
    end
  end

  private

  def month_number_for(month)
    (Date::MONTHNAMES.index(month.titleize) ||
     Date::ABBR_MONTHNAMES.index(month.titleize) || month).to_i
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def stats
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :authenticate

  def edit
    @profile = current_user
  end

  def update
    @profile = current_user
    if @profile.update_attributes(params[:user])
      redirect_to edit_profile_url, notice: 'Profile updated successfully'
    else
      render :edit
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in successfully"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out successfully"
  end

  def failure
    redirect_to sign_in_url, alert: 'Authentication failed, please try again.'
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authenticate
  before_filter :load_setting

  def edit
  end

  def update
    if @setting.update_attributes(params[:setting])
      redirect_to edit_settings_url, notice: 'Settings updated successfully'
    else
      render :edit
    end
  end

  private

  def load_setting
    @setting = current_user.setting || current_user.build_setting
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

  def twitter_blueprint_alert_type(type)
    return 'error' if type == :alert
    return 'success' if type == :notice
    return type
  end

  def friendly_date(date)
    day = date.strftime('%e')
    "#{date.strftime('%A')} #{ActiveSupport::Inflector.ordinalize(day)} #{date.strftime('%B %Y')}"
  end

  def previous_week(current_year, current_week_number)
    previous_week_number = current_week_number.to_i - 1
    previous_year = current_year.to_i
    if previous_week_number < 1
      previous_week_number = 52
      previous_year -= 1
    end
    [previous_year, previous_week_number]
  end

  def next_week(current_year, current_week_number)
    next_week_number = current_week_number.to_i + 1
    next_year = current_year.to_i
    if next_week_number > 52
      next_week_number = 1
      next_year += 1
    end
    [next_year, next_week_number]
  end

end

app/views/identities/new.html.haml
- title 'Sign up'

= simple_form_for @identity, url: '/auth/identity/register' do |f|
  = f.input :name, input_html: {name: 'name'}
  = f.input :email, input_html: {name: 'email'}
  = f.input :password, input_html: {name: 'password'}
  = f.input :password_confirmation, label: 'Confirm Password', input_html: {name: 'password_confirmation'}

  .form-actions
    = f.button :submit, 'Sign up', class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = content_for?(:title) ? yield(:title) : "Welcome!"
      = " - "
      Five Year Diary

    %meta(name="viewport" content="width=device-width")

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render partial: 'shared/analytics'

  %body
    = render partial: 'shared/navigation'

    .container-fluid
      .content
        .page-header
          - if content_for?(:title)
            %h1= yield(:title)

        - flash.each do |type, message|
          %div(class="alert alert-#{twitter_blueprint_alert_type(type)}")= message


        = yield

    %footer
      %p
        What would you like to see? Contact me
        = link_to '@sermoa', 'http://twitter.com/sermoa'
        with your ideas.

app/views/notes/_note.html.haml
.note(id="#{note.dom_id}")
  %h2= friendly_date(note.date)
  %ul.note-actions.unstyled
    %li.edit-note= link_to 'Edit note', edit_note_path(note)
  = auto_link(simple_format(note.content), html: {target: '_blank'})

app/views/notes/day.html.haml
- title "Notes made on #{ActiveSupport::Inflector.ordinalize(@date.strftime('%e'))} #{@date.strftime('%B')}"

%ul.navigation-actions
  %li.previous
    - previous_day = @date - 1.day
    = link_to 'previous day', daily_diary_path(previous_day.strftime('%B').downcase, previous_day.day)
  %li
    = link_to 'Add a note on this day', new_note_path(date: @date.strftime('%Y-%m-%d'))
  %li.next
    - next_day = @date + 1.day
    = link_to 'next day', daily_diary_path(next_day.strftime('%B').downcase, next_day.day)

.notes= render @notes

app/views/notes/day_of_month.html.haml
- title "Notes made on day #{@day} of each month"

%ul.navigation-actions
  %li.previous
    - previous_day = @day - 1
    - previous_day = 31 if previous_day < 1
    = link_to "day #{previous_day}", day_of_month_diary_path(previous_day)
  %li.next
    - next_day = @day + 1
    - next_day = 1 if next_day > 31
    = link_to "day #{next_day}", day_of_month_diary_path(next_day)

.notes= render @notes

app/views/notes/edit.html.haml
- title 'Edit note'

= simple_form_for @note do |f|

  = f.input :content, placeholder: "Write whatever is on your mind, as much or as little as you want ...", wrapper_html: {class: 'freetext'}
  = f.input :date, as: :string

  .form-actions
    = f.button :submit, 'Update note', class: 'btn-primary'

app/views/notes/new.html.haml
- title "Add a note"

= simple_form_for @note do |f|

  = f.input :content, placeholder: "Write whatever is on your mind, as much or as little as you want ...", wrapper_html: {class: 'freetext'}

  - date = @note.date
  - date = Date.parse(params[:date]) if params[:date]
  = f.input :date, as: :string, input_html: {value: date || DateTime.current.strftime('%Y-%m-%d')}

  .form-actions
    = f.button :submit, 'Save note', class: 'btn-primary'

app/views/notes/week.html.haml
:ruby
  previous_year, previous_week_number = previous_week(params[:year], params[:week_number])
  next_year, next_week_number = next_week(params[:year], params[:week_number])

- title "Notes made in week #{params[:week_number]} of #{params[:year]}"

%ul.navigation-actions
  %li.previous
    = link_to 'previous week', week_diary_path(previous_year, previous_week_number)
  %li.next
    = link_to 'next week', week_diary_path(next_year, next_week_number)

.notes
  - @notes.partition{|n| n.date.strftime('%u').to_i < 5}.each do |collection|
    .half
      - collection.each do |note|
        = render note

app/views/notes/week_day.html.haml
- title "Notes made on #{@weekday.strftime('%A').pluralize}"

%ul.navigation-actions
  %li.previous
    - previous_day = (@weekday - 1.day).strftime('%A').pluralize
    = link_to previous_day, week_day_diary_path(previous_day.downcase)
  %li.next
    - next_day = (@weekday + 1.day).strftime('%A').pluralize
    = link_to next_day, week_day_diary_path(next_day.downcase)

.notes= render @notes

app/views/pages/home.html.haml
- title 'Welcome to your Online Five Year Diary'

%p This will be your personal five year diary where you can write your thoughts every day of the year.

%p As the years go by you will be able to see at a glance how you were feeling on the same day on previous years.

%p Everything you write is private: this is not a blog. It's a chance for you to express your personal feelings in as many or as few words as you like.

%p
  If you're ready to begin, please
  - if user_signed_in?
    = link_to "write today's note", new_note_path

  - else
    = link_to 'sign up', sign_up_path

app/views/pages/stats.html.haml
- title 'Stats'

%table.bordered-table
  %thead
    %tr
      %th Query
      %th Value

  %tbody
    %tr
      %th Number of users
      %td= User.count

    %tr
      %th Number of notes
      %td= Note.count

    %tr
      %th Number of notes written today
      %td= Note.written_today.count

app/views/profiles/edit.html.haml
- title 'Edit Profile'

= simple_form_for @profile, url: profile_path do |f|

  = f.input :name

  .form-actions
    = f.button :submit, 'Update profile', class: 'btn-primary'

app/views/settings/edit.html.haml
- title 'Edit settings'

= simple_form_for @setting, url: settings_path, method: :put do |f|

  = f.input :time_zone, priority: /US|London/, input_html: {class: 'xxlarge'}, hint: "Currently #{current_user.time_zone} where it is #{I18n.l Time.zone.now, format: :long}"

  .form-actions
    = f.button :submit, 'Update settings', class: 'btn-primary'

app/views/shared/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28061774-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_authentication.html.haml
%ul.nav.pull-right
  - if user_signed_in?
    %li.dropdown
      = link_to "Hello #{current_user.name}", '#', class: 'dropdown-toggle'
      %ul.dropdown-menu
        %li= link_to 'Edit profile', edit_profile_path
        %li= link_to 'Edit settings', edit_settings_path
        %li.divider
        %li= link_to 'Sign out', sign_out_path

  - else
    %li= link_to 'Sign up', sign_up_path
    %li= link_to 'Sign in', sign_in_path

app/views/shared/_navigation.html.haml
.navbar.navbar-static-top
  .navbar-inner
    .container-fluid
      = link_to 'Five Year Diary', root_path, class: 'brand'

      %ul.nav
        %li
          = link_to 'Home', root_path

        - if user_signed_in?

          %li
            = link_to 'Add a note', new_note_path

          %li.dropdown
            = link_to 'View', '#', class: 'dropdown-toggle'
            %ul.dropdown-menu
              - date = DateTime.current
              %li= link_to 'Today', daily_diary_path(date.strftime('%B').downcase, date.day)
              %li= link_to 'This week', week_diary_path(date.strftime('%G'), date.strftime('%V').to_i)
              %li= link_to "Day #{date.day} of each month", day_of_month_diary_path(date.day)

              %li.divider

              - %w(Mondays Tuesdays Wednesdays Thursdays Fridays Saturdays Sundays).each do |week_day|
                %li= link_to week_day, week_day_diary_path(week_day.downcase)

      = render partial: 'shared/authentication'